version: '2'
services:
    catalogvalidator-app:
        image: catalogvalidator
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://catalogvalidator-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=CatalogValidator
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://catalogvalidator-elasticsearch:9200
        ports:
            - 8080:8080
    catalogvalidator-mongodb:
        extends:
            file: mongodb.yml
            service: catalogvalidator-mongodb
    catalogvalidator-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: catalogvalidator-elasticsearch
